spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/friend?serverTimezone=UTC&characterEncoding=UTF-8
    password: '1234'
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: cookie